import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import State from "./Context/State";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Laptop Price Predictor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <State>
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </State>
    </html>
  );
}
